#!/usr/bin/env python3

import socket
from pathlib import Path
from time import sleep


# The absolute minimum YAML parsing to avoid a depending on a YAML library.
def get_mqtt_address(config_path):
    if not config_path.exists():
        return None

    state = "init"

    with open(config_path) as f:
        for line in f:
            if state == "init":
                if line.startswith("mqtt:"):
                    state = "mqtt_section"
                continue
            if state == "mqtt_section":
                if not line.startswith(" "):
                    # End of MQTT section, no address found
                    return None
                if "server:" in line:
                    return line.split(":", 1)[1].strip()
                continue

    return None


mqtt_host = get_mqtt_address(Path("data") / "configuration.yaml")

if mqtt_host is None:
    # We didn't find the MQTT configuration, so we can't check it. Maybe Z2M
    # isn't configured yet. We don't know for sure so we don't block further
    # operations.
    exit(0)

address, _, maybe_port = mqtt_host.replace("mqtt://", "").partition(":")

try:
    port = int(maybe_port) if maybe_port else 1883
except ValueError:
    exit(0)


try:
    with socket.create_connection((address, port), timeout=5):
        exit(0)
except Exception as e:
    pass

sleep(5)
exit(1)
