#!/usr/bin/env bash

# This is the only script you need to run if you want to install Zigbee2MQTT in
# a largely self-contained manner.
#
# Executing this script sets up a Python virtual environment in the working
# directory, installs nodeenv, an appropriate version of node, pnpm, clones a
# particular version of Zigbee2MQTT, and creates a run script and service
# installation script.

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# Configuration. I'll update these values from time to time.
#
# This can be an exact or approximate version. pzg-setup-venv will pick the best
# match.
USE_PYTHON_VERSION="3.12"

# This needs to be an exact version that nodeenv knows about.
USE_NODE_VERSION="22.22.0"

ZIGBEE2MQTT_VERSION="2.6.1"
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# Script constants
SELF_DIR="$(cd "$(dirname "$0")"; pwd)"
SETUP_VENV_SCRIPT="$SELF_DIR/pzg-setup-venv"
RUN_Z2M_SCRIPT="$(pwd)/pzg-run-z2m"
START_SERVICE_SCRIPT="$(pwd)/pzg-install-and-start-z2m-as-a-service"
STOP_SERVICE_SCRIPT="$(pwd)/pzg-stop-and-uninstall-z2m-as-a-service"
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# Setup logging and error reporting
SCRIPT_NAME="$(basename "$0")"
COMMAND_BUFFER="$(mktemp)"
RED="\033[0;31m"
NC="\033[0m" # No Color

trap "rm -f "$COMMAND_BUFFER EXIT

log_info() {
    echo "[$SCRIPT_NAME]: $1" | fold -s -w "$(tput cols)"
}

log_error() {
    echo -e "${RED}[$SCRIPT_NAME]: ERROR: $1${NC}" | fold -s -w "$(tput cols)" >&2
}

log_error_dump() {
    echo -e "${RED}$1${NC}" >&2
}

log_warning() {
    echo -e "${RED}[$SCRIPT_NAME]: WARNING: $1${NC}" | fold -s -w "$(tput cols)" >&2
}
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

$SETUP_VENV_SCRIPT $USE_PYTHON_VERSION
source .venv/bin/activate

log_info "Installing nodeenv into the local Python virtual environment."
if ! pip install nodeenv > "$COMMAND_BUFFER" 2>&1; then
    log_error "Failed to install nodeenv using 'pip install nodeenv'"
    log_error "During the failed operation the following output was emitted:"
    log_error "--------------------"
    log_error_dump "$(cat "$COMMAND_BUFFER")"
    exit 1
fi

log_info "Installing node.js version $USE_NODE_VERSION using nodeenv."
if ! nodeenv -p -n $USE_NODE_VERSION > "$COMMAND_BUFFER" 2>&1; then
    log_error "Failed to node version $USE_NODE_VERSION using 'nodeenv -p -n $USE_NODE_VERSION'"
    log_error "During the failed operation the following output was emitted:"
    log_error "--------------------"
    log_error_dump "$(cat "$COMMAND_BUFFER")"
    exit 1
fi

# The -p switch instructed nodeenv add node.js related stuff to the virtual
# environment. We reactivate the venv to ensure that nodeenv added paths are
# also active.
deactivate
source .venv/bin/activate

log_info "Installing pnpm using npm."
if ! npm install pnpm --save-dev > "$COMMAND_BUFFER" 2>&1; then
    log_error "Failed to install pnpm using 'npm install pnpm --save-dev'"
    log_error "During the failed operation the following output was emitted:"
    log_error "--------------------"
    log_error_dump "$(cat "$COMMAND_BUFFER")"
    exit 1
fi

export PATH="$(pwd)/node_modules/.bin:$PATH"

log_info "Cloning zigbee2mqtt version $ZIGBEE2MQTT_VERSION"
if ! git clone --depth 1 --branch $ZIGBEE2MQTT_VERSION https://github.com/Koenkk/zigbee2mqtt.git > "$COMMAND_BUFFER" 2>&1; then
    log_error "Failed to download zigbee2mqtt using 'git clone --depth 1 --branch ZIGBEE2MQTT_VERSION https://github.com/Koenkk/zigbee2mqtt.git'"
    log_error "During the failed operation the following output was emitted:"
    log_error "--------------------"
    log_error_dump "$(cat "$COMMAND_BUFFER")"
    exit 1
fi

pushd zigbee2mqtt &> /dev/null;

log_info "Installing zigbee2mqtt"
if ! pnpm install --frozen-lockfile > "$COMMAND_BUFFER" 2>&1; then
    log_error "Failed to install zigbee2mqtt using 'pnpm install --frozen-lockfile'"
    log_error "During the failed operation the following output was emitted:"
    log_error "--------------------"
    log_error_dump "$(cat "$COMMAND_BUFFER")"
    exit 1
fi

popd &> /dev/null;

MQTT_PRECHECK_SCRIPT="$(pwd)/check-if-z2m-mqtt-is-listening"

cat << 'HERE_DOCUMENT_MARK' > "$MQTT_PRECHECK_SCRIPT"
#!/usr/bin/env python3

# YOU ARE NOT SUPPOSED TO MANUALLY CALL THIS SCRIPT
#
# It is used by install-z2m to determine if the MQTT server in its configuration
# is up and running. This way a service manager can avoid starting Zigbee2MQTT
# before the MQTT server is up, avoiding missing device information observed
# in version 2.6.1.

import socket
from pathlib import Path
from time import sleep


# The absolute minimum YAML parsing to avoid a dependency on a YAML library.
def get_mqtt_address(config_path):
    if not config_path.exists():
        return None

    state = "init"

    with open(config_path) as f:
        if "network_key: GENERATE" in f.read():
            # The configuration file is still in its default state, so we can't be
            # sure about the MQTT configuration. Maybe Z2M isn't configured yet.
            # We don't know for sure so we don't block further operations.
            return None

        for line in f:
            if state == "init":
                if line.startswith("mqtt:"):
                    state = "mqtt_section"
                continue
            if state == "mqtt_section":
                if not line.startswith(" "):
                    # End of MQTT section, no address found
                    return None
                if "server:" in line:
                    return line.split(":", 1)[1].strip()
                continue

    return None


mqtt_host = get_mqtt_address(Path("data") / "configuration.yaml")

if mqtt_host is None:
    # We didn't find the MQTT configuration, so we can't check it. Maybe Z2M
    # isn't configured yet. We don't know for sure so we don't block further
    # operations.
    exit(0)

address, _, maybe_port = mqtt_host.replace("mqtt://", "").partition(":")

try:
    port = int(maybe_port) if maybe_port else 1883
except ValueError:
    exit(0)


try:
    with socket.create_connection((address, port), timeout=5):
        exit(0)
except Exception as e:
    pass

sleep(5)
exit(1)
HERE_DOCUMENT_MARK

chmod u+x "$MQTT_PRECHECK_SCRIPT"

cat << 'HERE_DOCUMENT_MARK' > "$RUN_Z2M_SCRIPT"
#!/usr/bin/env bash

SELF_DIR="$(cd "$(dirname "$0")"; pwd)"
cd "$SELF_DIR"
source .venv/bin/activate
export PATH="$(pwd)/node_modules/.bin:$PATH"
cd zigbee2mqtt

if ! "$SELF_DIR/check-if-z2m-mqtt-is-listening"; then
    echo "Error: MQTT broker is not listening. Please start the MQTT broker before running zigbee2mqtt."
    exit 1
fi

pnpm start
HERE_DOCUMENT_MARK

chmod u+x "$RUN_Z2M_SCRIPT"

cat << 'HERE_DOCUMENT_MARK' > "$START_SERVICE_SCRIPT"
#!/bin/bash

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# Configuration.
SERVICE_NAME="io.zigbee2mqtt"
SERVICE_PATH="$HOME/Library/LaunchAgents/$SERVICE_NAME.plist"
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# Script constants
SELF_DIR="$(cd "$(dirname "$0")"; pwd)"
RUN_Z2M_SCRIPT="$SELF_DIR/pzg-run-z2m"
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# Setup logging and error reporting
SCRIPT_NAME="$(basename "$0")"
COMMAND_BUFFER="$(mktemp)"
RED="\033[0;31m"
NC="\033[0m" # No Color

trap "rm -f "$COMMAND_BUFFER EXIT

log_info() {
    echo "[$SCRIPT_NAME]: $1" | fold -s -w "$(tput cols)"
}

log_error() {
    echo -e "${RED}[$SCRIPT_NAME]: ERROR: $1${NC}" | fold -s -w "$(tput cols)" >&2
}

log_error_dump() {
    echo -e "${RED}$1${NC}" >&2
}

log_warning() {
    echo -e "${RED}[$SCRIPT_NAME]: WARNING: $1${NC}" | fold -s -w "$(tput cols)" >&2
}
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

if [[ "$(uname)" != "Darwin" ]]; then
    log_error "This script is only supported on macOS."
    return 0
fi

$SELF_DIR/pzg-stop-and-uninstall-z2m-as-a-service

log_info "Installing zigbee2mqtt service at $SERVICE_PATH"

cat << HEREDOC > "$SERVICE_PATH"
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$SERVICE_NAME</string>

    <key>ProgramArguments</key>
    <array>
        <string>$RUN_Z2M_SCRIPT</string>
    </array>

    <key>WorkingDirectory</key>
    <string>$SELF_DIR</string>

    <key>RunAtLoad</key>
    <true/>

    <key>KeepAlive</key>
    <true/>

    <key>StandardOutPath</key>
    <string>/tmp/$SERVICE_NAME/stdout.log</string>

    <key>StandardErrorPath</key>
    <string>/tmp/$SERVICE_NAME/stderr.log</string>
</dict>
</plist>
HEREDOC

log_info "Loading service..."
launchctl load $SERVICE_PATH

if [ $? -ne 0 ]; then
    echo "[pyziggy-setup] Error: Failed to load service $SERVICE_PATH"
    exit 1
else
    echo "[pyziggy-setup] Done."
    echo "[pyziggy-setup] Service logs are saved to /tmp/$SERVICE_NAME/stdout.log and /tmp/$SERVICE_NAME/stderr.log"
fi
HERE_DOCUMENT_MARK

chmod u+x "$START_SERVICE_SCRIPT"

cat << 'HERE_DOCUMENT_MARK' > "$STOP_SERVICE_SCRIPT"
#!/bin/bash

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# Configuration.
SERVICE_NAME="io.zigbee2mqtt"
SERVICE_PATH="$HOME/Library/LaunchAgents/$SERVICE_NAME.plist"
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# Script constants
SELF_DIR="$(cd "$(dirname "$0")"; pwd)"
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# Setup logging and error reporting
SCRIPT_NAME="$(basename "$0")"
COMMAND_BUFFER="$(mktemp)"
RED="\033[0;31m"
NC="\033[0m" # No Color

trap "rm -f "$COMMAND_BUFFER EXIT

log_info() {
    echo "[$SCRIPT_NAME]: $1" | fold -s -w "$(tput cols)"
}

log_error() {
    echo -e "${RED}[$SCRIPT_NAME]: ERROR: $1${NC}" | fold -s -w "$(tput cols)" >&2
}

log_error_dump() {
    echo -e "${RED}$1${NC}" >&2
}

log_warning() {
    echo -e "${RED}[$SCRIPT_NAME]: WARNING: $1${NC}" | fold -s -w "$(tput cols)" >&2
}
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

if [[ "$(uname)" != "Darwin" ]]; then
    log_error "This script is only supported on macOS."
    return 0
fi

mkdir -p ~/Library/LaunchAgents

if [ -f "$SERVICE_PATH" ] && (launchctl list | grep -q "$SERVICE_NAME"); then
    log_info "Stopping and removing $SERVICE_NAME..."
    launchctl unload "$SERVICE_PATH" && rm $SERVICE_PATH

    if [ $? -ne 0 ]; then
        log_error "Failed to unload and remove service $SERVICE_PATH"
        exit 1
    else
        log_info "Done."
    fi

    rm /tmp/$SERVICE_NAME/stdout.log
    rm /tmp/$SERVICE_NAME/stderr.log
else
    log_info "No $SERVICE_NAME installation found."
fi
HERE_DOCUMENT_MARK

chmod u+x "$STOP_SERVICE_SCRIPT"

cat << HERE_DOCUMENT_MARK > "UNINSTALL.md"
This directory contains a self-contained Zigbee2MQTT installation.

The Zigbee2MQTT configuration can be found in the \`zigbee2mqtt/data\` directory.
If you want to keep it, make sure to back up this directory before uninstalling.
You can copy this directory into a fresh installation to restore the
configuration.

To uninstall Zigbee2MQTT, first run \`./pzg-stop-and-uninstall-z2m-as-a-service\`
to stop the service and remove it.

Then you can delete this entire directory. This installation depends on \`pnpm\`.
If you aren't using it for anything else, you can also delete the pnpm store
directory: '$(pnpm store path)'."
HERE_DOCUMENT_MARK

log_info "Installation complete. See UNINSTALL.md for instructions about uninstalling."
log_info "You can install zigbee2mqtt as a service and launch it by issuing:"
log_info "    ./pzg-install-and-start-z2m-as-a-service"
